CREATE SCHEMA app DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
 /*- --User----------------------------*/
CREATE  TABLE APS_USER  (
   ID  BIGINT(20) NOT NULL AUTO_INCREMENT ,
   DELFLAG  TINYINT(1) NOT NULL ,
   MOBILE  VARCHAR(20) NULL ,
   PASSWORD  VARCHAR(50) NULL ,
   ROLE  INT(11) NULL ,
   ADDRESS  VARCHAR(200) NULL ,
   BIRTHDAY  DATETIME NULL ,
   CITY  INT(4) NULL ,
   EMAIL  VARCHAR(100) NULL ,
   NICK_NAME  VARCHAR(50) NULL ,
   PHOTO  VARCHAR(100) NULL ,
   REAL_NAME  VARCHAR(20) NULL ,
   IS_MAN  TINYINT(11) NULL ,
   MACHINE_CODE  VARCHAR(100) NULL ,
   AMOUNT  DOUBLE NOT NULL DEFAULT 0 ,
   IP  VARCHAR(20) NULL ,
   APP_VERSION  VARCHAR(50) NULL ,
  PRIMARY KEY ( ID ) ,
  UNIQUE INDEX  ID_UNIQUE  ( ID  ASC) ,
  INDEX  MOBILE  ( MOBILE  ASC) ,
  INDEX  CITY  ( CITY  ASC) ,
  INDEX  EMAIL  ( EMAIL  ASC) ,
  INDEX  NICK_NAME  ( NICK_NAME  ASC) ,
  INDEX  IS_MAN  ( IS_MAN  ASC) );

  ALTER TABLE  APS_USER  ADD COLUMN  CREATE_TIME  VARCHAR(45) NULL, ADD INDEX  CREATE_TIME  ( CREATE_TIME  ASC) ;
  ALTER TABLE APS_USER ADD COLUMN AGE TINYINT(10) NULL  , CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME NULL DEFAULT NULL  , ADD INDEX AGE (AGE ASC) ;

 /*- --任务----------------------------*/
  CREATE  TABLE  CMS_USER_TASK  (
   ID  BIGINT(20) NOT NULL AUTO_INCREMENT ,
   DELFLAG  TINYINT(4) NULL ,
   CREATE_TIME  DATETIME NULL ,
   APPROVER_ID  BIGINT(20) NOT NULL ,
   STATUS  TINYINT(4) NULL ,
   UPDATE_TIME  DATETIME NULL ,
  PRIMARY KEY ( ID ) ,
  UNIQUE INDEX  ID_UNIQUE  ( ID  ASC) ,
  INDEX  CREATE_TIME  ( CREATE_TIME  ASC) ,
  INDEX  DELFLAG  ( DELFLAG  ASC) ,
  INDEX  APPROVER_ID  ( APPROVER_ID  ASC) ,
  INDEX  STATUS  ( STATUS  ASC) );
  
ALTER TABLE CMS_USER_TASK ADD COLUMN TOTAL_STEP TINYINT(255) NOT NULL  AFTER UPDATE_TIME , CHANGE COLUMN APPROVER_ID APPROVER_ID BIGINT(20) NULL  
, ADD INDEX TOTAL_STEP (TOTAL_STEP ASC) ;

  ALTER TABLE CMS_USER_TASK ADD COLUMN BEGIN_TIME DATETIME NULL  AFTER TOTAL_STEP , ADD COLUMN END_TIME DATETIME NULL  AFTER BEGIN_TIME 
, ADD INDEX BEGIN_TIME (BEGIN_TIME ASC) 
, ADD INDEX END_TIME (END_TIME ASC) ;

 /*- --任务详情----------------------------*/
CREATE  TABLE CMS_USER_TASK_DETAIL (
  ID BIGINT(20) NOT NULL ,
  DELFLAG VARCHAR(45) NULL ,
  CREATE_TIME DATETIME NULL ,
  USER_TASK_ID BIGINT(20) NULL ,
  STEP TINYINT(255) NULL ,
  BEGIN_TIME DATETIME NULL ,
  END_TIME DATETIME NULL ,
  STATUS TINYINT(4) NULL ,
  PRIMARY KEY (ID) ,
  UNIQUE INDEX ID_UNIQUE (ID ASC) ,
  INDEX DELFLAG (DELFLAG ASC) ,
  INDEX CREATE_TIME (CREATE_TIME ASC) ,
  INDEX BEGIN_TIME (BEGIN_TIME ASC) ,
  INDEX STEP (STEP ASC) ,
  INDEX END_TIME (END_TIME ASC) ,
  INDEX STATUS (STATUS ASC) );

