CREATE SCHEMA app DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
use app;
 /*- --User----------------------------*/
CREATE  TABLE APS_USER  (
   ID  BIGINT(20) NOT NULL AUTO_INCREMENT ,
   DELFLAG  TINYINT(1) NOT NULL ,
   MOBILE  VARCHAR(20) NULL ,
   PASSWORD  VARCHAR(50) NULL ,
   ROLE  INT(11) NULL ,
   ADDRESS  VARCHAR(200) NULL ,
   BIRTHDAY  DATETIME NULL ,
   CITY  INT(4) NULL ,
   EMAIL  VARCHAR(100) NULL ,
   NICK_NAME  VARCHAR(50) NULL ,
   PHOTO  VARCHAR(100) NULL ,
   REAL_NAME  VARCHAR(20) NULL ,
   IS_MAN  TINYINT(11) NULL ,
   MACHINE_CODE  VARCHAR(100) NULL ,
   AMOUNT  DOUBLE NOT NULL DEFAULT 0 ,
   IP  VARCHAR(20) NULL ,
   APP_VERSION  VARCHAR(50) NULL ,
  PRIMARY KEY ( ID ) ,
  UNIQUE INDEX  ID_UNIQUE  ( ID  ASC) ,
  INDEX  MOBILE  ( MOBILE  ASC) ,
  INDEX  CITY  ( CITY  ASC) ,
  INDEX  EMAIL  ( EMAIL  ASC) ,
  INDEX  NICK_NAME  ( NICK_NAME  ASC) ,
  INDEX  IS_MAN  ( IS_MAN  ASC) );

  ALTER TABLE  APS_USER  ADD COLUMN  CREATE_TIME  VARCHAR(45) NULL, ADD INDEX  CREATE_TIME  ( CREATE_TIME  ASC) ;
  ALTER TABLE APS_USER ADD COLUMN AGE TINYINT(10) NULL  , CHANGE COLUMN CREATE_TIME CREATE_TIME DATETIME NULL DEFAULT NULL  , ADD INDEX AGE (AGE ASC) ;

 