ALTER TABLE APS_BLOG
DROP COLUMN MODIFY_TIMES,
ADD COLUMN MODIFY_TIMES  tinyint(1) NOT NULL DEFAULT 0 AFTER VERSION_ID,
ADD UNIQUE INDEX ID (ID) ,
ADD INDEX USER_ID (USER_ID) ,
ADD INDEX VERSION_ID (VERSION_ID) ,
ADD INDEX DELFLAG (DELFLAG) ,
ADD INDEX CREATE_TIME (CREATE_TIME) ;

ALTER TABLE APS_USER
ADD UNIQUE INDEX ID (ID) ,
ADD INDEX CREATE_TIME (CREATE_TIME) ,
ADD INDEX CITY_ID (CITY_ID) ,
ADD UNIQUE INDEX USER_NAME (USER_NAME) ,
ADD INDEX DELFLAG (DELFLAG) ,
ADD UNIQUE INDEX EMAIL (EMAIL) ,
ADD UNIQUE INDEX MOBILE (MOBILE) ;


ALTER TABLE APS_BLOG_VERSION
ADD UNIQUE INDEX ID (ID) ,
ADD INDEX USER_ID (USER_ID) ;

ALTER TABLE SYS_USER
ADD UNIQUE INDEX ID (ID) ,
ADD INDEX CREATE_TIME (CREATE_TIME) ,
ADD INDEX DELFLAG (DELFLAG) ,
ADD UNIQUE INDEX EMAIL (EMAIL) ,
ADD UNIQUE INDEX MOBILE (MOBILE) ;

ALTER TABLE SYS_USER
ADD COLUMN PHOTO  varchar(255) NULL AFTER MOBILE;

ALTER TABLE APS_USER
ADD COLUMN PHOTO  varchar(255) NULL AFTER CITY_STR;


ALTER TABLE SYS_USER
MODIFY COLUMN DEL_TIME  timestamp NULL DEFAULT NULL;

ALTER TABLE SYS_USER
MODIFY COLUMN DELFLAG  tinyint(1) NULL DEFAULT 0 ;

ALTER TABLE `sys_user`
MODIFY COLUMN `ROLE`  int(11) NULL DEFAULT 0 AFTER `PASSWORD`;

ALTER TABLE `aps_user`
MODIFY COLUMN `DEL_TIME`  timestamp NULL DEFAULT NULL AFTER `DELFLAG`;






